### PR TITLE
Updating all package dependencies

### PR DESCRIPTION
**Pull request by dsgouda**
- Updating xunit package references
- targeting the netstandard1.3 framework since we do not use dotnet anymore
- updating netstandard libraries' references
- updating the dotnet cli installation version 

There are still compilation errors in the cli component which needs resolution but packages can be generated which have been successfully tested
@lt72 @MattGal @davmason

### CODE REVIEW

**Comment by davmason** [comment]
What are the compilation errors in the cli? We shouldn't check in changes unless the project builds clean.

**Comment by dsgouda** [comment]
@dotnet-bot Test this

**Comment by dsgouda** [comment]
@dotnet-bot Test this please

**Comment by dsgouda** [comment]
@dotnet-bot Test this please

**Comment by dsgouda** [comment]
@dotnet-bot Test this please

**Comment by lt72** [comment]
👍

**Pull request merged**
