### PR TITLE
Add xunit.core to the windows runner

### PR DESCRIPTION
**Pull request by pharring**
xunit.core is missing from the Windows runner.

### CODE REVIEW

**Comment by pharring** [comment]
@dotnet-bot test this again, please

**Comment by pharring** [comment]
@dotnet-bot test this

**Comment by ericeil** [comment]
:+1:

**Comment by pharring** [comment]
@dotnet-bot re-test this

**Comment by pharring** [comment]
Will re-open to try and re-trigger Jenkins builds.

**Pull request merged**
