### PR TITLE
Move to xunit 2.1.0 final

### PR DESCRIPTION
**Pull request by ericeil**
- Move to xunit 2.1.0 final
- Move to dnx.xunit 2.1.0-beta5a
- Fix a couple of build/project issues

### CODE REVIEW

**Comment by ericeil** [comment]
@pharring, @mellinoe, @ianhays

**Comment by pharring** [comment]
:+1:

**Comment by pharring** [comment]
.. although take note of the Jenkins failure in Debug. Is that due to the change in the .MSBuild file where you build packages even for Debug builds?

**Comment by ericeil** [comment]
Yes, the build issue was legit.  Added a commit that should fix this.

**Comment by ericeil** [comment]
@dotnet-bot test this please

**Comment by ericeil** [comment]
@mellinoe, @ianhays, are you ok with moving to the final xunit 2.1.0 release?

**Comment by ianhays** [comment]
I haven't investigated what the changes that Release brings yet, but I'd imagine we want to move to eventually. With that said, I'll likely be too busy finding/squashing perf bugs to make the upgrade until ~2 weeks from now at least. I'll let Eric chime in on what he thinks though.

**Comment by mellinoe** [comment]
I don't see any reason why we couldn't upgrade. Assuming there haven't been any assemblies renamed or breaking changes in the xUnit API, it should be fairly straightforward. I wouldn't be able to do it any time soon, but I don't think there's anything blocking us from moving to it when we need the latest perf tools

**Comment by ericeil** [comment]
There are no breaking changes, as far as I can tell.  There are actually very, very few changes since RC1.
Thanks all, I'll go ahead with this.

**Pull request merged**
