### PR TITLE
Building cli projects for netstandard1.3

### PR DESCRIPTION
**Pull request by dsgouda**
netcoreapp1.0 is not supported with dnxcore50 for certain projects in CoreFX, building for netstandard1.3 instead which is supported instead
Adding DotNetCliVersion.txt to control what version of dotnet cli we are using

@brianrob @lt72

### CODE REVIEW

**Comment by dsgouda** [comment]
@dotnet-bot Test this please

**Comment by dsgouda** [comment]
@dotnet-bot Test Debug Build please

**Comment by dsgouda** [comment]
@dotnet-bot Test this please

**Comment by dsgouda** [comment]
@dotnet-bot Test Release Build please

**Comment by dsgouda** [comment]
@dotnet-bot Test this please

**Comment by dsgouda** [comment]
@dotnet-bot Test this please

**Comment by dsgouda** [comment]
@dotnet-bot Test this please

**Comment by brianrob** [comment]
@dsgouda, does this leave the * for netcoreapp in the project.json files for each of the CLI-built projects?  I think this will still result in the issue referenced by #127.

**Comment by dsgouda** [comment]
@brianrob I have hardcoded the NetCoreApp references to point to the shared framework we install while installing dotnet cli for building the cli projects (002520)

**Comment by brianrob** [comment]
Perfect.  LGTM.

@dpodder, this is the full fix, so let's close your PR in favor of this one.

@dsgouda, let's get this merged ASAP as @dpodder is dependent on it.  Thanks!

**Pull request merged**
